config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post 'users/guest/sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root "homes#top"
    get "homes/about" => "homes#about", as: 'about'

    resources :posts, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      collection do
        get "following"
      end
    end

    get "users/mypage" => "users#index", as: 'mypage'
    get "users/:id/information/edit" => "users#edit", as: 'edit_information'
    patch "users/:id" => "users#update", as: 'update_information'
    put "users/:id/information" => "users#update" 

    resources :users, only: [:show, :destroy] do
      resource :relationships, only: [:create, :destroy]

      member do
        get :likes
      end

      member do
        get :following, :follower
      end
    end
  end

  get "search" => "searches#search"


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @word = params[:word]

    if @model == "User"
      @users = User.looks(params[:word])
    else
      @posts = Post.looks(params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<%= form_with url: search_path, local: true, method: :get, class:"d-flex flex-column flex-sm-row align-items-center" do |f| %>
  <%= f.text_field :word %>
  <%= f.select :model, options_for_select([['ユーザー','User'], ['投稿','Post']]), {}, class:"mt-2 mt-sm-0 ml-sm-2" %>
  <%= f.submit "検索", class: "btn btn-outline-primary btn-sm mt-2 mt-sm-0 ml-sm-2" %>
<% end %>

app/views/searches/search.html.erb
<div class="container">
<% if @model == "User" %>
  <div class="row d-flex justify-content-center">
    <h2 class="user result mb-3"> 名前に"<%= @word %>"を含むユーザーの検索結果</h2>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-3"></div>
    <div class="col-6">
    <% @users.each do |user| %>
      <table class = "table border">
        <thead>
          <tr>
            <th></th>
            <th>ユーザー名</th>
            <th>ポスト数</th>
            <th>最新ポスト投稿日</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(50,50) %></td>
            <td><%= user.name %></td>
            <td><%= user.posts.count %></td>
            <td><%= user.posts.last&.created_at&.strftime('%Y/%m/%d') || '投稿なし' %></td>
            <td><%= link_to "詳細を見る", user_path(user.id) %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
    </div>
    <div class="col-3"></div>
  </div>
<% else %>
  <div class="row">
    <h2 class="post result"> 感想に"<%= @word %>"を含むポストの検索結果</h2>
  </div>
  <div class="row d-flex justify-content-center">
    <% @posts.each do |post| %>
      <table class = "table border">
        <tr>
          <th>
            <%= link_to user_path(post.user.id) do %>
              <% if post.user.profile_image.attached? %>
                <%= image_tag post.user.profile_image, size: "50x50" %>
              <% else %>
                <%= image_tag asset_path("no_image.jpg"), size: "50x50" %>
              <% end %>
            <% end %>
          </th>
          <td><big><%= post.user.name %></big></td>
        </tr>
        <tr><th>日付</th> <td><%= post.date %></td></tr>
        <tr><th>体重</th> <td><%= post.weight %>kg</td></tr>
        <tr><th>BMI</th> <td><%= (post.weight.to_i / (post.user.height.to_i * post.user.height.to_i * 0.0001)).round(2) %></td></tr>
        <tr><th>歩数</th> <td><%= post.step %>歩</td></tr>
        <tr><th>食事内容</th> <td><%= post.food_i18n %></td></tr>
        <tr><th>感想</th> <td><%= safe_join(post.text.split("\n"),tag(:br)) %></td></tr>
        <tr><th></th><td><%= link_to "詳細", post_path(post.id) %></td></tr>
      </table>
    <% end %>
  </div>
<% end %>
</div>