config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post 'users/guest/sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root "homes#top"
    get "homes/about" => "homes#about", as: 'about'

    resources :posts, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      collection do
        get "following"
      end
    end

    get "users/mypage" => "users#index", as: 'mypage'
    get "users/:id/information/edit" => "users#edit", as: 'edit_information'
    patch "users/:id" => "users#update", as: 'update_information'
    put "users/:id/information" => "users#update" 

    resources :users, only: [:show, :destroy] do
      resource :relationships, only: [:create, :destroy]

      member do
        get :likes
      end

      member do
        get :following, :follower
      end
    end
  end

  get "search" => "searches#search"


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  
  has_many :following_users, through: :active_relationships, source: :following
  has_many :follower_users, through: :passive_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true
  validates :gender, presence: true
  validates :height, presence: true
  validates :weight, presence: true

  enum gender: { male: 1, female: 2, blank:0 }

  def self.looks(word)
    @user = User.where("name LIKE?", "%#{word}%")
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    active_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(following_id: user_id)&.destroy
  end

  def following?(user)
    following_users.include?(user)
  end

  def bmi
    (weight.to_f / (height.to_f * height.to_f * 0.0001)).round(2)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.gender = "blank"
      user.height = "171"
      user.weight = "64"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザー削除完了'
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :gender, :height, :weight, :introduction, :goal)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <h2 class="mb-4">ユーザー</h2>
  </div>
  <div class="row">
    <% @users.each do |user| %>
      <table class = "table border">
        <thead>
          <tr>
            <th></th>
            <th>ユーザー名</th>
            <th>投稿数</th>
            <th>アカウント作成日</th>
            <th>最新投稿投稿日</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(50,50) %></td>
            <td><%= user.name %></td>
            <td><%= user.posts.count %></td>
            <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= user.posts.last&.created_at&.strftime('%Y/%m/%d') || '投稿なし' %></td>
            <td><%= link_to "詳細を見る", admin_user_path(user.id) %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center mt-3">
    <div class="col-3">
      <div class="sticky">
        <%= render "public/users/profile", user: @user %>
        <div class="withdraw mt-3 mb-3">
          <%= link_to "退会させる", admin_user_path(@user.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に退会させますか？" %>
        </div>
      </div>
    </div>

    <div class="col-9">
      <div class="row d-flex justify-content-center">
        <div class="form">
          <% @user.posts.each do |post| %>
            <table class = "table border">
              <tr>
                <th>
                  <%= image_tag post.user.get_profile_image(50,50) %>
                </th>
                <td><big><%= post.user.name %></big></td>
              </tr>
              <tr><th>日付</th> <td><%= post.date %></td></tr>
              <tr><th>体重</th> <td><%= post.weight %>kg</td></tr>
              <tr><th>BMI</th> <td> <%= post.bmi %> </td></tr>
              <tr><th>歩数</th> <td><%= post.step %>歩</td></tr>
              <tr><th>食事内容</th> <td><%= post.food_i18n %></td></tr>
              <tr><th>感想</th> <td><%= safe_join(post.text.split("\n"),tag(:br)) %></td></tr>
              <tr><th></th><td><%= link_to "詳細", admin_post_path(post.id) %></td></tr>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>