config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post 'users/guest/sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root "homes#top"
    get "homes/about" => "homes#about", as: 'about'

    resources :posts, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      collection do
        get "following"
      end
    end

    get "users/mypage" => "users#index", as: 'mypage'
    get "users/:id/information/edit" => "users#edit", as: 'edit_information'
    patch "users/:id" => "users#update", as: 'update_information'
    put "users/:id/information" => "users#update" 

    resources :users, only: [:show, :destroy] do
      resource :relationships, only: [:create, :destroy]

      member do
        get :likes
      end

      member do
        get :following, :follower
      end
    end
  end

  get "search" => "searches#search"


end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <p class="dynapuff mt-2 mb-2">
      <big>nikki</big> 〜<strong>肉</strong>体改造交換日<strong>記</strong>〜
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <% if admin_signed_in? %>
      <%= link_to about_path do %>
        <%= image_tag "transparentLogo.png", size: "90x90" %>
      <% end %>
    <% elsif user_signed_in? %>
      <%= link_to about_path do %>
        <%= image_tag "transparentLogo.png", size: "90x90" %>
      <% end %>
    <% else %>
      <%= link_to root_path do %>
        <%= image_tag "transparentLogo.png", size: "90x90" %>
      <% end %>    
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">

        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to '投稿一覧', admin_posts_path, class: 'btn hover-scale' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ユーザー一覧', admin_users_path, class: 'btn hover-scale' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_admin_session_path, class: 'btn hover-scale', method: :delete %>
          </li>

        <% elsif user_signed_in? %>
          <li class="nav-item">
            <%= link_to posts_path, class: 'btn hover-scale' do %>
              <i class="fa-solid fa-timeline"></i>タイムライン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: 'btn hover-scale' do %>
              <i class="fa-solid fa-pen-to-square"></i>投稿する
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to mypage_path, class:"btn hover-scale" do %>
              <i class="fa-solid fa-user"></i>マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to likes_user_path(current_user.id), class: 'btn hover-scale' do %>
              <i class="fa-solid fa-heart"></i>いいね一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, class: 'btn hover-scale', method: :delete, data: { turbo: false } do %>
              <i class="fa-solid fa-right-from-bracket"></i>ログアウト
            <% end %>
          </li>
          
        <% else %>
          <li class="nav-item">
            <%= link_to about_path, class: 'btn hover-scale' do %>
              <i class="fa-solid fa-link"></i>About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'btn hover-scale' do %>
              <i class="fa-solid fa-right-to-bracket"></i>ログイン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'btn hover-scale' do %>
              <i class="fa-solid fa-user-plus"></i>新規登録
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_scroll_top_btn.html.erb
<span id="back" class="d-none d-md-block">
  <a href="#" class="scroll-top-btn">
    <i class="fa-solid fa-circle-up"></i>
  </a>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nikki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5a2608659f.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=DynaPuff:wght@400..700&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %> 
    </header>

    <main class="<%= yield :main_class %>">
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
      <%= yield %>
    </main>
 
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    
  </body>
</html>